version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - springboot_network

networks:
  springboot_network:
    driver: bridge

volumes:
    data: